name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}  
        script: |
          cd /appvanture/appventure_frontend/
          sudo lsof -ti :3000 | xargs kill -9 2>/dev/null || true
          git pull origin main
          npm install
          npm run build
          pm2 restart appventure_front
